name = "selge"
compatibility_date = "2024-04-04"

[[d1_databases]]
binding = "selge_d1"
database_name = "selge"
database_id = "6fd6e9b1-e767-419b-b157-32045884d25b"

[[kv_namespaces]]
binding = "selge_kv"
id = "95ab8bf561794c42800ac15847134ba2"

[[r2_buckets]]
binding = "selge_r2"
bucket_name = "selge"
preview_bucket_name = "selge"
